# Generated by Django 3.2.7 on 2021-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverimages',
            options={'verbose_name': 'Örtük şəkili', 'verbose_name_plural': 'Örtük şəkilləri'},
        ),
        migrations.AddField(
            model_name='coverimages',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Başlıq'),
            preserve_default=False,
        ),
    ]
