# Generated by Django 3.2.7 on 2021-09-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210918_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('job', models.CharField(max_length=100, verbose_name='İş')),
                ('image', models.ImageField(upload_to='teams')),
                ('facebook', models.CharField(blank=True, max_length=1000)),
                ('twitter', models.CharField(blank=True, max_length=1000)),
                ('instagram', models.CharField(blank=True, max_length=1000)),
                ('linkedin', models.CharField(blank=True, max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Komanda',
                'verbose_name_plural': 'Komandalar',
            },
        ),
        migrations.AlterField(
            model_name='coverimages',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Başlıq'),
        ),
    ]
