# Generated by Django 3.2.7 on 2021-09-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210918_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('servicepoints', models.IntegerField()),
                ('workers', models.IntegerField()),
                ('clients', models.IntegerField()),
                ('projectsompleted', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Paylaşılıb'), ('draft', 'Qaralama')], max_length=100)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fakt',
                'verbose_name_plural': 'Faktlar',
            },
        ),
    ]
