# Generated by Django 3.2.7 on 2021-09-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('job', models.CharField(max_length=100, verbose_name='İş')),
                ('image', models.ImageField(upload_to='client')),
                ('message', models.TextField(verbose_name='Şərh')),
                ('status', models.CharField(choices=[('active', 'Paylaşılıb'), ('draft', 'Qaralama')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müştəri şərhi',
                'verbose_name_plural': 'Müştəri şərhləri',
            },
        ),
        migrations.AlterField(
            model_name='facts',
            name='clients',
            field=models.IntegerField(verbose_name='Müştəri məmuniyyəti'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='projectsompleted',
            field=models.IntegerField(verbose_name='Tamamlanmış işlər'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='servicepoints',
            field=models.IntegerField(verbose_name='Servis sayı'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='workers',
            field=models.IntegerField(verbose_name='İşçi sayı'),
        ),
    ]
