# Generated by Django 3.2.7 on 2021-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Ünvan')),
                ('is_main', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Paylaşılıb'), ('draft', 'Qaralama')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
