# Generated by Django 3.2.7 on 2021-09-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Location',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Ünvan', 'verbose_name_plural': 'Ünvanlar'},
        ),
    ]
