# Generated by Django 3.2.7 on 2021-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_location_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('price', models.IntegerField(verbose_name='Qiymət')),
                ('text', models.TextField(verbose_name='Paketə daxildir:')),
                ('status', models.CharField(choices=[('active', 'Paylaşılıb'), ('draft', 'Qaralama')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qiymət Paketlər',
                'verbose_name_plural': 'Qiymət Paketlər',
            },
        ),
    ]
