# Generated by Django 3.2.7 on 2021-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210921_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Ünvan və parametr', 'verbose_name_plural': 'Ünvan və parametrlər'},
        ),
        migrations.AddField(
            model_name='location',
            name='open_hour',
            field=models.CharField(blank=True, max_length=100, verbose_name='İş saatı:'),
        ),
    ]
