# Generated by Django 3.2.7 on 2021-09-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Mövzu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('false', 'Baxılmayıb'), ('true', 'Baxılıb')], default='false', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqə',
            },
        ),
    ]
