# Generated by Django 3.2.7 on 2021-09-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya adı')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaradıldığı tarix')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('image', models.ImageField(upload_to='blogphotos', verbose_name='Şəkil')),
                ('text', models.TextField(max_length=100, verbose_name='Mətin')),
                ('status', models.CharField(choices=[('active', 'Paylaşılıb'), ('draft', 'Qaralama')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorymodel', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloqlar',
            },
        ),
    ]
