# Generated by Django 3.2.7 on 2021-09-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Göndərilyi tarix'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='Məqalə'),
        ),
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('email', models.CharField(max_length=100, verbose_name='Elektron poçt')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Göndərilyi tarix')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='Məqalə')),
            ],
            options={
                'verbose_name': 'Cavab',
                'verbose_name_plural': 'Cavab',
            },
        ),
    ]
