# Generated by Django 3.2.7 on 2021-09-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210922_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replycomments',
            options={'verbose_name': 'Şərh cavabı', 'verbose_name_plural': 'Şərh cavabları'},
        ),
        migrations.RemoveField(
            model_name='replycomments',
            name='post',
        ),
    ]
