# Generated by Django 3.2.7 on 2021-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('status', models.CharField(choices=[('True', 'Qəbul edilib'), ('False', 'Gözləmədə')], max_length=100, verbose_name=(('True', 'Qəbul edilib'), ('False', 'Gözləmədə')))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rezerv',
                'verbose_name_plural': 'Rezervlər',
            },
        ),
    ]
