# Generated by Django 3.2.7 on 2021-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210919_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('True', 'Qəbul edilib'), ('False', 'Gözləmədə')], default='False', max_length=100, verbose_name='Status'),
        ),
    ]
