# Generated by Django 3.2.7 on 2021-09-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210921_1356'),
        ('reservation', '0003_alter_reservationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.price'),
            preserve_default=False,
        ),
    ]
