# Generated by Django 3.2.7 on 2021-09-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservationmodel_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='plan',
        ),
    ]
