# Generated by Django 3.2.7 on 2021-09-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_reservationmodel_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə tarixi'),
        ),
    ]
